name: checker_account
version: 1.1.0
publish_to: none
description: A checker account app.
environment:
   sdk: ">=3.3.4 <4.0.0"

dependencies:
   cupertino_icons: ^1.0.6
   http: ^1.2.1
   get: 4.6.6
   flutter:
      sdk: flutter

dev_dependencies:
   flutter_lints: ^3.0.0
   flutter_test:
      sdk: flutter

flutter:
   uses-material-design: true
